{{- if .Values.preflight.crdChecks.enabled }}
{{- $required := list "streams.jetstream.nats.io" "consumers.jetstream.nats.io" "keyvalues.jetstream.nats.io" "objectstores.jetstream.nats.io" -}}
{{- range $crd := $required }}
{{- if not (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" $crd) }}
{{- fail (printf "Required CRD %s not found. Install NACK CRDs first (helm/charts/nack/crds)." $crd) }}
{{- end }}
{{- end }}
{{- end }}
