---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{.Release.Name}}-stan'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{.Values.stan.serviceName}}'
spec:
  clusterIP: '{{.Values.stan.clusterIP}}'
  ports:
  - name: client
    port: {{.Values.stan.clientPort}}
  - name: cluster
    port: {{.Values.stan.clusteringPort}}
  - name: monitor
    port: {{.Values.stan.webuiPort}}
  - name: metrics
    port: {{.Values.prometheus.metricsPort}}
  selector:
    app: '{{.Release.Name}}-stan'
