---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{.Chart.Name}}-stan-config'

data:
  stan.conf: |-
    http: {{.Values.stan.webuiPort}}

    {{- if .Values.stan.enableClustering }}
    cluster {
      port: {{.Values.stan.clusteringPort}}
      routes [
        nats://{{.Values.stan.serviceName}}:{{.Values.stan.clusteringPort}}
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 10
    }
    {{- end }}

    {{- if .Values.stan.authToken }}
    authorization {
      token: '{{.Values.stan.authToken}}'
    }
    {{- end}}

    streaming {
      id: '{{.Values.stan.clusterID}}'
      ft_group_name: '{{.Values.stan.ftGroup}}'
      {{- if eq .Values.stan.store "sql"}}
      store: "sql"

      sql_options {
        driver: "postgres"
        source: '{{.Values.stan_sql.source}}'
      }
      {{- else }}
      store: "file"
      dir: /data/stan/store

      {{- end}}
    }
