apiVersion: v2
name: nack-resources
version: 0.0.1
description: A Helm chart for NACK resources - Install NATS JetStream resources (Streams, Consumers, KeyValues, ObjectStores) via NACK CRDs
sources:
  - https://github.com/nats-io/nack
  - https://github.com/nats-io/k8s
keywords:
  - nats
  - jetstream
  - nack
  - streams
  - consumers
  - keyvalue
  - objectstore

