{
 "title": "NATS Surveyor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(nats_core_info, server_cluster)"
   },
   {
    "name": "expected",
    "query": "query_result(nats_survey_expected_count)"
   }
  ]
 },
 "panels": [
  {
   "title": "Received Messages",
   "type": "singlestat",
   "description": "Combined messages received by all servers",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nats_core_recv_msgs_count[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "singlestat",
   "description": "Combined messages sent by all servers",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_msgs_count[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "description": "Combined bytes received by all servers",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nats_core_recv_bytes[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "description": "Combined bytes sent by all servers",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_bytes[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "Total current connections across all servers",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nats_core_connection_count)"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "singlestat",
   "description": "Slow consumers seen per second",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nats_core_slow_consumer_count[1m]))",
     "legendFormat": "Slow"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "singlestat",
   "description": "Number of known clusters",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nats_core_info) by (server_cluster))",
     "legendFormat": "Servers"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "singlestat",
   "description": "Number of known servers",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(nats_core_info)", "legendFormat": "Servers" }
   ]
  },
  {
   "title": "Route Connections",
   "type": "singlestat",
   "description": "Number of routes reported as active",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nats_core_route_count)" }
   ]
  },
  {
   "title": "Gateway Connections",
   "type": "singlestat",
   "description": "Number of routes reported as active",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nats_core_gateway_count)", "legendFormat": "Gateways" }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Cluster Connections",
   "type": "graph",
   "description": "Combined current connections",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(nats_core_connection_count)",
     "legendFormat": "Connections"
    },
    { "expr": "sum(nats_core_subs_count)", "legendFormat": "Subscriptions" }
   ]
  },
  {
   "title": "Cluster Slow Consumers",
   "type": "graph",
   "description": "Combined slow consumers detected per second",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_core_slow_consumer_count[1m]))",
     "legendFormat": "Slow Consumers"
    }
   ]
  },
  {
   "title": "Cluster Message Traffic",
   "type": "graph",
   "description": "Combined total messages for all servers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_msgs_count[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_recv_msgs_count[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "graph",
   "description": "Combined cluster network usage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_core_sent_bytes[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(nats_core_recv_bytes[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Server Versions",
   "type": "graph",
   "description": "Distribution of NATS Server Versions across the cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nats_core_info) by (server_version)",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "Cluster RTT",
   "type": "heatmap",
   "description": "RTT times for the cluster as observed from the Surveyor",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "nats_core_rtt_nanoseconds", "legendFormat": "RTT" }
   ]
  },
  {
   "title": "Client Connection Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections",
     "type": "graph",
     "description": "Point in time view of clients connected to each Server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "current connections" }
     ],
     "targets": [
      { "expr": "nats_core_connection_count", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "Active Subscriptions",
     "type": "graph",
     "description": "Number of subscriptions active on the server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "subscriptions" }
     ],
     "targets": [
      { "expr": "nats_core_subs_count", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "Connections per second",
     "type": "graph",
     "description": "Connections received by the server in a second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "connections / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_total_connection_count[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Subscription Delta",
     "type": "graph",
     "description": "The difference in subscription count per minute",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "subscriptions" }
     ],
     "targets": [
      {
       "expr": "delta(nats_core_subs_count[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Slow Consumers",
     "type": "graph",
     "description": "Slow consumers detected by each server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "slow / second" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_slow_consumer_count[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway Bytes Sent",
     "type": "graph",
     "description": "Bytes sent for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_gateway_sent_bytes[1m])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Bytes Received",
     "type": "graph",
     "description": "Bytes received for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_gateway_recv_bytes[1m])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Messages Sent",
     "type": "graph",
     "description": "Messages sent for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_gateway_sent_msgs_count[1m])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    },
    {
     "title": "Gateway Messages Received",
     "type": "graph",
     "description": "Messages received for each gateway",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_gateway_recv_msg_count[1m])",
       "legendFormat": "{{server_name}} - {{server_cluster}} -> {{server_gateway_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Route Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Route Bytes Sent",
     "type": "graph",
     "description": "Bytes sent for each route",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_bytes[1m])",
       "legendFormat": "{{server_name}} - ID {{server_route_id}}"
      }
     ]
    },
    {
     "title": "Route Bytes Received",
     "type": "graph",
     "description": "Bytes received for each route",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_bytes[1m])",
       "legendFormat": "{{server_name}} - ID {{server_route_id}}"
      }
     ]
    },
    {
     "title": "Route Messages Sent",
     "type": "graph",
     "description": "Messages sent for each route",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_sent_msg_count[1m])",
       "legendFormat": "{{server_name}} - ID {{server_route_id}}"
      }
     ]
    },
    {
     "title": "Route Messages Received",
     "type": "graph",
     "description": "Messages received for each route",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "messages / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_route_recv_msg_count[1m])",
       "legendFormat": "{{server_name}} - ID {{server_route_id}}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "graph",
     "description": "The number of servers in each cluster",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "cluster size" }
     ],
     "targets": [
      {
       "expr": "sum(nats_core_info) by (server_cluster)",
       "legendFormat": "{{server_cluster}}"
      }
     ]
    },
    {
     "title": "Route Pending Data",
     "type": "graph",
     "description": "Data in the pending buffers that needs to be sent to remotes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nats_core_route_pending_bytes",
       "legendFormat": "{{server_name}} - {{server_route_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent",
     "type": "graph",
     "description": "Data sent per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      { "expr": "rate(nats_core_sent_bytes[1m])", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "Bytes Received",
     "type": "graph",
     "description": "Data received per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      { "expr": "rate(nats_core_recv_bytes[1m])", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "Messages Sent",
     "type": "graph",
     "description": "Messages sent per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_sent_msgs_count[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Messages Received",
     "type": "graph",
     "description": "Messages received per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_recv_msgs_count[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU used by the NATS Server process",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "cpu %" }
     ],
     "targets": [
      { "expr": "nats_core_cpu_percentage", "legendFormat": "{{server_name}}" }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "The number of bytes in use by the NATS server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      { "expr": "nats_core_mem_bytes", "legendFormat": "{{server_name}}" }
     ]
    }
   ]
  },
  {
   "title": "Surveyor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expected vs Received",
     "type": "graph",
     "description": "The number of NATS Servers expected to reply vs how many replied during a poll",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Expected" }
     ],
     "targets": [
      { "expr": "nats_survey_expected_count", "legendFormat": "Expected" },
      { "expr": "nats_survey_surveyed_count", "legendFormat": "Responded" }
     ]
    },
    {
     "title": "Cluster RTT",
     "type": "graph",
     "description": "Cluster wide RTT as calculated from the Surveyor",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ns", "label": "RTT" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_rtt_nanoseconds[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "NATS Reconnects",
     "type": "graph",
     "description": "Number of times the surveyor reconnected to the network in a minute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(nats_survey_nats_reconnects[5m])",
       "legendFormat": "Reconnections"
      }
     ]
    },
    {
     "title": "Poll Time",
     "type": "graph",
     "description": "Time it takes the surveyor to gather the statistics from surveyed NATS Servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "s", "label": "time per poll" }
     ],
     "targets": [
      {
       "expr": " rate(nats_survey_duration_seconds_sum[5m])\n/\n  rate(nats_survey_duration_seconds_count[5m])",
       "legendFormat": "Poll Time"
      }
     ]
    }
   ]
  }
 ]
}