apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "nats.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "nats.selectorLabels" $ | nindent 4 }}
  ports:
  {{- range $protocol := list "nats" "leafnodes" "websocket" "mqtt" "cluster" "gateway" "monitor" "profiling" }}
  {{- $configProtocol := get $.Values.config $protocol }}
  {{- $servicePort := get $.Values.service.ports $protocol }}
  {{- if and (or (eq $protocol "nats") $configProtocol.enabled) $servicePort.enabled }}
  - {{ merge (dict "name" $protocol "targetPort" $protocol) (omit $servicePort "enabled") (dict "port" $configProtocol.port) | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
