apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-kafka.fullname" . }}-config
  namespace: {{ include "nats-kafka.namespace" . }}
  labels:
    {{- include "nats-kafka.labels" . | nindent 4 }}
data:
  nats-kafka.conf: |
    reconnectinterval: {{ .Values.natskafka.reconnectInterval }}
    connecttimeout: {{ .Values.natskafka.connectTimeout }}

    logging: {
      time: {{ .Values.natskafka.logging.time }},
      debug: {{ .Values.natskafka.logging.debug }},
      trace: {{ .Values.natskafka.logging.trace }},
      colors: {{ .Values.natskafka.logging.colors }},
      pid: {{ .Values.natskafka.logging.pid }},
    }

    nats: {
      Servers: [
        {{- range .Values.natskafka.nats.servers }}
        "{{ . }}",
        {{- end }}
      ],
      ConnectTimeout: {{ .Values.natskafka.nats.connectTimeout }},
      MaxReconnects: {{ .Values.natskafka.nats.maxReconnects }},
      ReconnectWait: {{ .Values.natskafka.nats.reconnectWait }},
      {{- with .Values.natskafka.nats.credentials }}
      UserCredentials: /etc/nats-kafka/creds/{{ .secret.key }},
      {{- end }}
    }

    {{ if or .Values.natskafka.monitoring.httpPort .Values.natskafka.monitoring.httpsPort }}
    monitoring: {
      {{ with .Values.natskafka.monitoring.httpHost }}httpHost: {{ . }}{{ end -}}
      {{ with .Values.natskafka.monitoring.httpPort }}httpPort: {{ . }}{{ end -}}
      {{ with .Values.natskafka.monitoring.httpsPort }}httpsPort: {{ . }}{{ end -}}
      {{ if and .Values.natskafka.monitoring.tls.cert .Values.natskafka.monitoring.tls.key }}
      tls: {
        {{ with .Values.natskafka.monitoring.tls.root }}root: /etc/nats-kafka/tls/{{ . }}{{ end }}
        {{ with .Values.natskafka.monitoring.tls.cert }}cert: /etc/nats-kafka/tls/{{ . }}{{ end }}
        {{ with .Values.natskafka.monitoring.tls.key }}key: /etc/nats-kafka/tls/{{ . }}{{ end }}
      }
      {{- end }}
    }
    {{- end }}

    connect: {{ toRawJson .Values.natskafka.connect | indent 4 }}
