{{- with .Values.config.resolver.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- with .storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
