{{- if .Values.config.jetstream.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-surveyor-accounts
  labels:
    {{- include "surveyor.labels" . | nindent 4 }}
data:
  {{- range .Values.config.jetstream.accounts }}
  {{ .name }}.json: |
    {
      "name": "{{ .name }}",
      {{- if .credential }}
      "credential": "{{ .credential }}"
      {{- end }}      
      {{- if .tls }}
      {{- if .tls.ca }}
      "tls_ca": "/etc/nats-certs/accounts/{{ .name }}/{{ .tls.ca }}",
      {{- end }}
      "tls_cert": "/etc/nats-certs/accounts/{{ .name }}/{{ .tls.cert }}",
      "tls_key": "/etc/nats-certs/accounts/{{ .name }}/{{ .tls.key }}"
      {{- end }}
    }
  {{- end }}
{{- end }}
